// src/presentations/HouseDatacenter/slides/SpeakerIntroSlides.vue
<script setup lang="ts">
import SlideTypeOne from '@/components/SlideTypeOne.vue';
</script>

<template>
    <SlideTypeOne>
        <h2>Quick Intro</h2>
        <ul>
            <li>Senior Software Engineer at Jack Henry</li>
            <li>President of Springfield Devs</li>
            <li>Co-organizer of Open SGF</li>
        </ul>
    </SlideTypeOne>
</template>

// src/routes/(presentations)/house-datacenter/slides/SpeakerIntroSlides.svelte
<script lang="ts">
    import SlideTypeOne from '$lib/components/SlideTypeOne.svelte';
</script>

<SlideTypeOne>
    <h2>Quick Intro</h2>
    <ul>
        <li>Senior Software Engineer at Jack Henry</li>
        <li>President of Springfield Devs</li>
        <li>Co-organizer of Open SGF</li>
    </ul>
</SlideTypeOne>
