// src/components/PresentationWrapper.vue
<script setup lang="ts">
import { ref } from 'vue';
import RevealPresentation from '@/components/RevealPresentation.vue';
import { useReveal } from '@/composables/useReveal';
import type { SlideTypes } from '@/slideTypes';
import { parseSlideType, slideTypes } from '@/slideTypes';
import TitleBackground from '@/components/backgrounds/TitleBackground.vue';
import TypeOneBackground from '@/components/backgrounds/TypeOneBackground.vue';
import TypeTwoBackground from '@/components/backgrounds/TypeTwoBackground.vue';

const { onReady } = useReveal();

const slideType = ref<SlideTypes>(slideTypes.none);

const updateSlideTypeFromSlide = (slide: HTMLElement) => {
    slideType.value = parseSlideType(slide.dataset.slideType);
};

onReady((reveal) => {
    updateSlideTypeFromSlide(reveal.getCurrentSlide());

    reveal.on('slidechanged', () => {
        updateSlideTypeFromSlide(reveal.getCurrentSlide());
    });
});
</script>

<template>
    <RevealPresentation>
        <template #decorations>
            <div class="background-container">
                <TitleBackground class="background" :active="slideType === slideTypes.title" />
                <TypeOneBackground class="background" :active="slideType === slideTypes.type1" />
                <TypeTwoBackground class="background" :active="slideType === slideTypes.type2" />
            </div>
            <div class="logo">
                <img src="@/assets/logo.svg" alt="Levi Zitting Logo" />
            </div>
        </template>
        <slot />
    </RevealPresentation>
</template>

<style scoped lang="scss">
.background-container,
.background {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.logo {
    position: absolute;
    bottom: 0;
    left: 0;
    transform: translate(5vw, -5vh);
    height: 10vh;
}
</style>

// src/lib/components/PresentationWrapper.svelte
<script lang="ts">
    import type { Snippet } from 'svelte';
    import RevealPresentation from './RevealPresentation.svelte';
    import TitleBackground from './backgrounds/TitleBackground.svelte';
    import TypeOneBackground from './backgrounds/TypeOneBackground.svelte';
    import TypeTwoBackground from './backgrounds/TypeTwoBackground.svelte';
    import { parseSlideType, slideTypes, type SlideTypes } from '$lib/slideTypes';
    import logo from '$lib/assets/logo.svg';

    let { children }: { children: Snippet } = $props();
    let slideType = $state<SlideTypes>(slideTypes.none);
</script>

<RevealPresentation
    onslidechange={(slide) => {
        slideType = parseSlideType(slide.dataset.slideType);
    }}
>
    {#snippet decorations()}
        <div class="absolute inset-0">
            <TitleBackground active={slideType === slideTypes.title} />
            <TypeOneBackground active={slideType === slideTypes.type1} />
            <TypeTwoBackground active={slideType === slideTypes.type2} />
        </div>
        <img class="absolute bottom-[5vh] left-[5vw] m-0 h-[10vh]" src={logo} alt="Levi Zitting Logo" />
    {/snippet}
    {@render children()}
</RevealPresentation>
